### ISSUE TITLE
Add dependencies in README

### ISSUE THREAD

**Issue by Pawamoy** [baskerville/xtitle#10]
Hi, just to say I had to install these to be able to make:

```
xcb
libxcb-keysyms1-dev
libxcb-util0-dev
libxcb-icccm4-dev
libxcb-ewmh-dev
```

You could maybe add a note about this in the README :smiley:

**Comment by Pawamoy** [comment]
No update, closing

**Comment by 8carlosf** [comment]
On problem with that is that package names differ from distro to distro, and as such I'm not sure about the correct way to describe the dependencies.
If adding it to the Readme file isn't a good optino, maybe dependencies.txt or requirements.txt
Also, in archlinux the sependencies are
`libxcb` and `xcb-util-wm`
