### ISSUE TITLE
xtitle doesn't clear title when last window is closed

### ISSUE THREAD

**Issue by zanculmarktum** [baskerville/xtitle#14]
I use xtitle in combination with dzen2, like this:
$ xtitle | dzen2

But when I close the last window (in current workspace), the title of the last window is remain.

**Comment by 8carlosf** [comment]
Pretty sure this is your setup, try xtitle on the terminal and see if it works okay.
If you care to share the exact commands and configs, I (or someone else) may be able to help.

**Comment by zanculmarktum** [comment]
Of course it would work on terminal, cause the terminal that run xtitle has its own title, so as soon as I closed the last window, the title would changed to it.
By the way this is my config:
xtitle -st 100 | dzen2 -ta c -w 780 -h 24 -e - -fn 'Cantarell:size=10' -bg '#e7e8eb' -fg '#5c616c' -dock

**Comment by 8carlosf** [comment]
well, you can open a terminal with xtitle in a workspace, move to another, close all windows there, and go back to the terminal to see the output. and it does print empty lines.
I also tested both this method, and closing all screens in a workspace (using dualscreen), and the configuration that you shared and all of them worked well :/
Can you try the method I suggested? leaving a terminal running xtitle in one workspace and close all windows in another, and go back check if there is an empty line there.
(I'm running low on ideas, sorry)

**Comment by zanculmarktum** [comment]
I think I've found the issue here.
The title wasn't cleared because xtitle doesn't print anything when there's no window.
That is, dzen only update its bar when the input (from xtitle) isn't empty.
So, to workaround this, xtitle needs to output a whitespace `" "` character to make dzen update its bar.
If you're great in C, consider to fix it, thanks.

**Comment by 8carlosf** [comment]
Hm, I tried dzen with your command and worked fine :/

Anyway, if you need to output a space before the title, you can use the format option

`xtitle -st 100 -f " %s \n"`

**Comment by zanculmarktum** [comment]
Doesn't work.
I have no idea why it's work for you.

**Comment by 8carlosf** [comment]
well, you can leave this issue open, but I'm 99% sure it isn't xtitle's fault

And I can't figure it out with the information I have...

one last try, run:
`nohup xtitle -st 100 -f " %s \n" | tee ~/XTITLELOG &`
do your thing, close all windows and all that stuff, maybe even more than once, open a terminal and `pkill xtitle` and share the XTITLELOG file.

**Comment by zanculmarktum** [comment]
Running your script:
` user@host: nohup `
Move to a new workspace: (as expected, empty)
`  `
Opening gvim:
` Vim `
gvim opened:
` [No Name] - GVIM1 `
Closing gvim: (xtitle just ignoring it, and didn't print anything)
` [No Name] - GVIM1 `
Reverting back to previous workspace:
` user@host: nohup`

So I think, when closing gvim, xtitle should outputs `" "`.

**Comment by 8carlosf** [comment]
Could you share the actual file it produced?

**Comment by zanculmarktum** [comment]
https://ptpb.pw/ljql
