### ISSUE TITLE
segfault on long titles

### ISSUE THREAD

**Issue by tertium** [baskerville/xtitle#15]
xtitle segfaults when the window title is longer than MAXLEN.

In get_window_title(), title_len can end up being set to MAXLEN, then mbsnrtowcs() fills out title[] and returns MAXLEN, and then
line 278:  title[title_len] = L'\0';
corrupts the memory after the end of the array.

The simplest fix IMO would be allocating title[] with MAXLEN+1 elements, to always leave space for the terminator.

Also, at line 300, "MAXLEN" should be replaced with "len", as get_window_title() is a generic function.

**Comment by baskerville** [comment]
I can't reproduce, what's the output of `xtitle -v`?

**Comment by tertium** [comment]
It's the current master tip, d244ff9907b451ec467cf121283586f13f7279d5.

You do not really need to reproduce the segfault itself. Just check that titles longer than MAXLEN make mbsnrtowcs() return MAXLEN, and then you know that line 278 is buggy.

**Comment by tertium** [comment]
I get a segfault, because the value of evt gets corrupted and then free(evt) at line 119 fails. Depending on your system and compiler, your variables may be laid out in a different manner, thus provoking different effects or none at all.

**Comment by tertium** [comment]
Ouch, I gave you a wrong line number, both in the original report and in the first reply!
The faulty assignment is at line 305.
