### ISSUE TITLE
Core dump on active window change, after negative truncation

### ISSUE THREAD

**Issue by j0ni** [baskerville/xtitle#19]
Happy path, with positive truncation:
```
joni@odo % xtitle -t 100 -s
scratchterm
/home/joni/Scratch/TheGuild/Motiva/backend-big-enos/test/backend_big_enos/lifecycle/motiva/activa...
scratchterm
/home/joni/Scratch/TheGuild/Motiva/backend-big-enos/test/backend_big_enos/lifecycle/motiva/activa...
scratchterm
^C
```

Unhappy path, with negative truncation:
```
joni@odo % xtitle -t -100 -s
scratchterm
...ratch/TheGuild/Motiva/backend-big-enos/test/backend_big_enos/lifecycle/motiva/activation_test.clj
munmap_chunk(): invalid pointer
[1]    1123 abort (core dumped)  xtitle -t -100 -s
```

**Comment by j0ni** [comment]
BTW I have a workaround (this is in the context of i3) where I remove the snoop setting and call xtitle every second. The output happens even when it dumps core, so I get what I need; now I just need a fix for this to salve my shame at such an awful hack :)

**Comment by 8carlosf** [comment]
https://github.com/baskerville/xtitle/blob/master/xtitle.c#L194
this seems to be the most likely problem.. it's changing the pointer, might break the free(title)

**Comment by j0ni** [comment]
@8carlosf looks like you're correct. I've no idea if it's good C, and I won't be offended @baskerville if you reject it, but the linked PR #20 seems to fix it for me.
